name: CI to Docker Hub

on:
  push:
    branches: [master]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    environment: Production
    steps:
      - uses: actions/checkout@v4.2.2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3.2.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.8.0

      - name: Login to Docker Hub
        uses: docker/login-action@v3.3.0
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v6.10.0
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: gameline/primevue-nuxt:latest
          build-args: |
            NUXT_GITHUB_TOKEN=${{ secrets.VITE_GITHUB_TOKEN }}
